version: '3'

services:
  socketgateway:
    container_name: strpg_api-gateway_socket
    build:
      context: ./packages/api-gateway-socket
      dockerfile: Dockerfile
    image: strpg_api-gateway_socket
    working_dir: /usr/src/app
    volumes:
      - ./packages/api-gateway-socket:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./packages/shared:/usr/src/app/node_modules/@text-game/shared
    command: npm run start
    restart: on-failure
    environment:
      NODE_ENV: development
    ports:
      - 8888:8888
    secrets:
      - main_secret
    networks:
      - webnet
    dns:
      - 8.8.8.8
    depends_on:
      - messagebroker
  main:
    container_name: strpg_mainly
    build:
      context: ./packages/main
      dockerfile: Dockerfile
    image: strpg_mainly
    working_dir: /usr/src/app
    volumes:
      - ./packages/main:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./packages/shared:/usr/src/app/node_modules/@text-game/shared
    command: npm run start
    restart: on-failure
    environment:
      NODE_ENV: development
    secrets:
      - main_secret
    networks:
      - webnet
    dns:
      - 8.8.8.8
    depends_on:
      - messagebroker
  messagebroker:
    container_name: strpg_message-broker
    image: rabbitmq:3.10.5-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    networks:
      - webnet
  shared:
    container_name: strpg_shared
    build:
      context: ./packages/shared
      dockerfile: Dockerfile
    image: strpg_shared
    working_dir: /usr/src/app
    volumes:
      - ./packages/shared:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: npm run compile:dev
    restart: on-failure
    environment:
      NODE_ENV: development
    networks:
      - webnet
    dns:
      - 8.8.8.8
  web-client:
    container_name: strpg_web-client
    build:
      context: ./packages/web-client
      dockerfile: Dockerfile
    image: strpg_web-client
    working_dir: /usr/src/app
    volumes:
      - ./packages/web-client:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./packages/shared:/usr/src/app/node_modules/@text-game/shared
    command: npm run dev
    restart: on-failure
    environment:
      NODE_ENV: development
    networks:
      - webnet
    dns:
      - 8.8.8.8
    ports:
      - 5173

  # postgres:
  #   container_name: postgres
  #   image: postgres:14
  #   networks:
  #     - webnet
  #   environment:
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_USER: ${DATABASE_USER}
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     PG_DATA: /var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  graphDBData:
  pgdata:
  rabbitmq_data:
  rabbitmq_log:
secrets:
  main_secret:
    file: .env.json